// ElectAssist — Gemini AI Service
// Handles all calls to Google Gemini AI API

import { SYSTEM_INSTRUCTION } from './mistral.js'; // Reuse the same instruction

class GeminiService {
  constructor(apiKey) {
    this.apiKey = apiKey;
    this.conversationHistory = [];
    this.modelName = "gemini-1.5-flash"; 
  }

  classifyIntent(message) {
    const lower = message.toLowerCase();
    if (/(timeline|schedule|phase|when is|date|deadline|calendar|upcoming)/.test(lower)) return "TIMELINE";
    if (/(register|registration|enroll|form 6|voter list|electoral roll|sign up)/.test(lower)) return "REGISTRATION";
    if (/(vote|voting|booth|polling station|how to vote|evm|vvpat|election day|bring|id|carry)/.test(lower)) return "VOTING";
    if (/(result|counting|winner|tally|declared|announced|majority|hung)/.test(lower)) return "RESULTS";
    if (/(what is|explain|definition|meaning|who is|eligible|can i|allowed)/.test(lower)) return "FAQ";
    return "GENERAL";
  }

  buildPrompt(userMessage) {
    const intent = this.classifyIntent(userMessage);
    const currentDate = new Date().toLocaleDateString("en-IN", { 
      weekday: "long", year: "numeric", month: "long", day: "numeric" 
    });

    const contextNote = `[Context: User query intent detected as ${intent}. Current date: ${currentDate}. Provide a helpful, accurate response about Indian elections.]`;
    return `${contextNote}\n\nUser: ${userMessage}`;
  }

  async sendMessage(userMessage) {
    this.conversationHistory.push({
      role: "user",
      parts: [{ text: this.buildPrompt(userMessage) }]
    });

    const url = `https://generativelanguage.googleapis.com/v1beta/models/${this.modelName}:generateContent?key=${this.apiKey}`;
    
    const requestBody = {
      systemInstruction: {
        parts: [{ text: SYSTEM_INSTRUCTION }]
      },
      contents: this.conversationHistory,
      generationConfig: {
        temperature: 0.7,
        topP: 0.95,
        maxOutputTokens: 1024,
      }
    };

    const response = await fetch(url, {
      method: "POST",
      headers: { 
        "Content-Type": "application/json"
      },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errorText = await response.text();
      let errorObj;
      try { errorObj = JSON.parse(errorText); } catch(e) {}
      throw new Error(errorObj?.error?.message || `Gemini API Error ${response.status}`);
    }

    const data = await response.json();
    const assistantMessage = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!assistantMessage) {
      throw new Error("No response generated by Gemini. Please try again.");
    }

    this.conversationHistory.push({
      role: "model",
      parts: [{ text: assistantMessage }]
    });

    if (this.conversationHistory.length > 20) {
      this.conversationHistory = this.conversationHistory.slice(-20);
    }

    return {
      text: assistantMessage,
      intent: this.classifyIntent(userMessage)
    };
  }

  clearHistory() {
    this.conversationHistory = [];
  }
}

export { GeminiService };
