// ElectAssist — Mistral AI Service
// Handles all calls to Mistral AI API

const MISTRAL_API_BASE = "https://api.mistral.ai/v1/chat/completions";

const SYSTEM_INSTRUCTION = `You are ElectAssist AI — a friendly, accurate, and strictly nonpartisan election education assistant. Your purpose is to help citizens understand the democratic process, election procedures, voter rights, and civic participation.

CORE RULES:
1. NEVER express political opinions or favor any party, candidate, or ideology
2. NEVER produce electoral misinformation or unverified claims  
3. ALWAYS use plain, accessible language (target: Grade 8 reading level)
4. ALWAYS be encouraging about civic participation
5. If asked about political opinions, redirect to the process/procedures
6. If you don't know something specific, acknowledge it and point to official sources

YOUR EXPERTISE COVERS:
- Voter registration process, eligibility, and deadlines
- Step-by-step voting procedures (what to bring, how EVMs work, VVPAT)
- Election timeline phases (announcement → MCC → nomination → campaign → polling → counting → results)
- Model Code of Conduct (MCC) rules and implications
- Candidate nomination process and requirements
- Vote counting methods and result declaration
- Voter rights and legal protections
- Polling booth location guidance
- Special voting (postal ballot, overseas voters, PwD, seniors)
- Electoral systems (FPTP, proportional representation)
- The role of the Election Commission
- How to report violations or grievances

RESPONSE STYLE:
- Use numbered steps for procedural questions
- Use bullet points for lists of requirements/documents
- Keep responses concise but complete (aim for 3-5 paragraphs max)
- End important responses with a relevant action suggestion
- Use emojis sparingly for warmth (1-2 per response max)

INTENT CATEGORIES you handle:
- TIMELINE: Questions about election schedule, phases, and dates
- REGISTRATION: How to register, eligibility, documents, deadlines
- VOTING: How to vote, polling day procedures, what to bring
- RESULTS: How counting works, how winners are decided
- FAQ: General election knowledge questions
- GENERAL: Civic education and democratic process questions
- OUT_OF_SCOPE: Clearly outside election education (politely redirect)`;

class MistralService {
  constructor(apiKey) {
    this.apiKey = apiKey;
    this.conversationHistory = [];
    // User requested "mistral small 2506"
    this.modelName = "mistral-small-2506"; 
  }

  // Classify intent from user message
  classifyIntent(message) {
    const lower = message.toLowerCase();
    if (/(timeline|schedule|phase|when is|date|deadline|calendar|upcoming)/.test(lower)) return "TIMELINE";
    if (/(register|registration|enroll|form 6|voter list|electoral roll|sign up)/.test(lower)) return "REGISTRATION";
    if (/(vote|voting|booth|polling station|how to vote|evm|vvpat|election day|bring|id|carry)/.test(lower)) return "VOTING";
    if (/(result|counting|winner|tally|declared|announced|majority|hung)/.test(lower)) return "RESULTS";
    if (/(what is|explain|definition|meaning|who is|eligible|can i|allowed)/.test(lower)) return "FAQ";
    return "GENERAL";
  }

  // Build context-enriched prompt
  buildPrompt(userMessage) {
    const intent = this.classifyIntent(userMessage);
    const currentDate = new Date().toLocaleDateString("en-IN", { 
      weekday: "long", year: "numeric", month: "long", day: "numeric" 
    });

    const contextNote = `[Context: User query intent detected as ${intent}. Current date: ${currentDate}. Provide a helpful, accurate response about Indian elections.]`;
    return `${contextNote}\n\nUser: ${userMessage}`;
  }

  async sendMessage(userMessage) {
    // Add user message to history
    this.conversationHistory.push({
      role: "user",
      content: this.buildPrompt(userMessage)
    });

    const requestBody = {
      model: this.modelName,
      messages: [
        { role: "system", content: SYSTEM_INSTRUCTION },
        ...this.conversationHistory
      ],
      temperature: 0.7,
      top_p: 0.95,
      max_tokens: 1024,
    };

    const response = await fetch(MISTRAL_API_BASE, {
      method: "POST",
      headers: { 
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.apiKey}`,
        "Accept": "application/json"
      },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errorText = await response.text();
      let errorObj;
      try {
        errorObj = JSON.parse(errorText);
      } catch(e) {}
      
      throw new Error(errorObj?.error?.message || `Mistral API Error ${response.status}`);
    }

    const data = await response.json();
    const assistantMessage = data.choices?.[0]?.message?.content;

    if (!assistantMessage) {
      throw new Error("No response generated by Mistral. Please try again.");
    }

    // Add assistant response to history
    this.conversationHistory.push({
      role: "assistant",
      content: assistantMessage
    });

    // Keep conversation history manageable (last 10 turns)
    if (this.conversationHistory.length > 20) {
      this.conversationHistory = this.conversationHistory.slice(-20);
    }

    return {
      text: assistantMessage,
      intent: this.classifyIntent(userMessage)
    };
  }

  clearHistory() {
    this.conversationHistory = [];
  }
}

// Input sanitization
function sanitizeInput(input) {
  if (typeof input !== "string") return "";
  let sanitized = input.trim().replace(/\s+/g, " ");
  sanitized = sanitized.slice(0, 500);
  sanitized = sanitized.replace(/<[^>]*>/g, "");
  return sanitized;
}

export { MistralService, sanitizeInput, SYSTEM_INSTRUCTION };
